- name: Download Abmra Soft from Blob
  shell: "az storage blob download --container-name {{ az_container_name }} --account-key {{ az_account_key }} --account-name {{ az_account_name }} -f {{ambra_gateway_install_directory}}setup-{{ ambra_gateway_version }}.exe --name {{ambra_gateway_download_url}}/setup-{{ ambra_gateway_version }}.exe"
  changed_when: false

